services:
  postgres:
    image: postgres:17
    container_name: webii_postgres
    environment:
      POSTGRES_USER: webii_tp2
      POSTGRES_PASSWORD: webii_tp2
      POSTGRES_DB: webii_tp2
    ports:
      - "5432:5432"
    restart: unless-stopped
